INSERT INTO USER (USERNAME, PASSWORD) VALUES ('duyl', '$2y$11$giHEpd8RRHqdDXuzQdfWo.Im4Gw3TEOqZTDkoBgiJi0VjHOoS2r/K');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('jdoe', '$2y$11$FAqw/FzQGBBLl.r/NWGOAeIQVodh6j9vIMWK/1l0YlZEyss43u6EG');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('duyl', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('duyl', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('jdoe', 'USER');